# Generated by Django 6.1 on 2026-08-31 19:31

import archethosbackend.apps.media_library.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document')], db_index=True, max_length=16)),
                ('source_type', models.CharField(choices=[('UPLOAD', 'Uploaded file'), ('YOUTUBE', 'YouTube')], default='UPLOAD', max_length=16)),
                ('file', models.FileField(blank=True, upload_to=archethosbackend.apps.media_library.models.upload_to)),
                ('external_url', models.URLField(blank=True, max_length=500)),
                ('external_id', models.CharField(blank=True, max_length=64)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, help_text='Describes the image for screen readers and search engines.', max_length=255)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['media_type', '-created_at'], name='media_libra_media_t_29eb84_idx'), models.Index(fields=['source_type'], name='media_libra_source__828a9f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('source_type', 'UPLOAD'), models.Q(('file', ''), _negated=True)), models.Q(('source_type', 'YOUTUBE'), models.Q(('external_url', ''), _negated=True)), _connector='OR'), name='media_asset_source_has_payload')],
            },
        ),
    ]
