# Generated by Django 6.1 on 2026-09-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='caption',
            field=models.CharField(blank=True, help_text='Shown beside the image where a layout has room for one.', max_length=500),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='description',
            field=models.TextField(blank=True, help_text='Internal notes: where it came from, usage rights, who is in it.'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
