# Generated by Django 6.1 on 2026-09-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_mediaasset_caption_mediaasset_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='media_location',
            field=models.CharField(choices=[('local', 'Local disk'), ('s3', 'S3-compatible object storage'), ('external', 'External URL or CDN')], db_index=True, default='local', max_length=16),
        ),
    ]
