# Generated by Django 6.1 on 2026-09-03 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0003_mediaasset_media_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mediaasset',
            name='media_asset_source_has_payload',
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='source_type',
            field=models.CharField(choices=[('UPLOAD', 'Uploaded file'), ('YOUTUBE', 'YouTube'), ('EXTERNAL', 'External URL')], default='UPLOAD', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_type', 'UPLOAD'), models.Q(('file', ''), _negated=True)), models.Q(('source_type__in', ['YOUTUBE', 'EXTERNAL']), models.Q(('external_url', ''), _negated=True)), _connector='OR'), name='media_asset_source_has_payload'),
        ),
    ]
