# Generated by Django 5.2 on 2026-09-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_library", "0001_initial"),
        ("master", "0006_galleryitem_title_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="hero_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="gallery",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gallery_hero_images",
                to="media_library.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="gallery",
            name="hero_title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
