# Generated by Django 6.1 on 2026-09-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_faq_timestamps'),
        ('master', '0011_move_blogs_to_blogs_app'),
    ]

    operations = [
    ]
