# Generated by Django 6.1 on 2026-09-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='featured_projects',
            field=models.ManyToManyField(blank=True, related_name='featured_on_projects_pages', to='projects.project'),
        ),
    ]
