# Generated by Django 6.1 on 2026-09-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_project_status'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='services',
        ),
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='projects', to='services.service'),
        ),
    ]
