# Generated by Django 6.1 on 2026-09-20 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_services_project_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
    ]
