# Generated by Django 6.1 on 2026-09-20 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_project_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='layout',
        ),
    ]
