# Generated by Django 6.1 on 2026-09-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_project_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetailedstage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
