# Generated by Django 6.1 on 2026-09-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projectdetailedstage_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='construction_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='outcome_note',
            field=models.TextField(blank=True),
        ),
    ]
