# Generated by Django 6.1 on 2026-09-20 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_construction_note_project_outcome_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='construction_note',
        ),
        migrations.RemoveField(
            model_name='project',
            name='outcome_note',
        ),
    ]
