# Generated by Django 6.1 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("projects", "0012_remove_project_construction_note_and_more")]

    operations = [
        migrations.AlterField(
            model_name="projectdetailedstage",
            name="description",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
