# Generated by Django 6.1 on 2026-09-24

import json

from django.db import migrations, models


def convert_descriptions_to_editorjs(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    for project in Project.objects.all().iterator():
        text = (project.description or "").strip()
        project.description = json.dumps({
            "blocks": [{"type": "paragraph", "data": {"text": text}}] if text else [],
        })
        project.save(update_fields=["description"])


class Migration(migrations.Migration):
    dependencies = [("projects", "0014_seed_project_categories")]

    operations = [
        migrations.RunPython(convert_descriptions_to_editorjs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
