# Generated by Django 6.1 on 2026-08-31 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_type', models.CharField(choices=[('hero', 'Hero'), ('intro', 'Studio intro'), ('counter', 'Counters / stats band'), ('featured_projects', 'Featured projects'), ('services', 'Services'), ('gallery', 'Gallery'), ('faq', 'FAQ'), ('cta', 'Call to action'), ('contact_info', 'Contact info'), ('rich_text', 'Rich text')], db_index=True, editable=False, help_text='Set automatically from the concrete model.', max_length=32)),
                ('internal_label', models.CharField(help_text='Admin-facing name, e.g. "Home - main hero" or "About - studio hero". Never shown on the public site; it exists so the section browser can tell several heroes apart.', max_length=255)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CounterSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeaturedProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('display_variant', models.CharField(blank=True, help_text='Optional per-placement hint, e.g. "large" or "compact".', max_length=32)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GallerySectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('caption', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('eyebrow', models.CharField(blank=True, help_text='e.g. "Architecture / Interiors / Build".', max_length=255)),
                ('heading', models.TextField(help_text='One line per row. Line breaks are preserved as written.')),
                ('lead', models.TextField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=100)),
                ('cta_url', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('label_override', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactInfoSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sections.section')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('office_hours', models.CharField(blank=True, max_length=255)),
                ('map_embed_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Contact info section',
            },
            bases=('sections.section',),
        ),
        migrations.CreateModel(
            name='CounterSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sections.section')),
                ('eyebrow', models.CharField(blank=True, max_length=255)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('subheading', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Counter section',
            },
            bases=('sections.section',),
        ),
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sections.section')),
                ('eyebrow', models.CharField(blank=True, max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('button_label', models.CharField(blank=True, max_length=100)),
                ('button_url', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'CTA section',
            },
            bases=('sections.section',),
        ),
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sections.section')),
                ('eyebrow', models.CharField(blank=True, max_length=255)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('subheading', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'FAQ section',
            },
            bases=('sections.section',),
        ),
        migrations.CreateModel(
            name='FeaturedProjectsSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sections.section')),
                ('eyebrow', models.CharField(blank=True, max_length=255)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('subheading', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Featured projects section',
            },
            bases=('sections.section',),
        ),
        migrations.CreateModel(
            name='GallerySection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sections.section')),
                ('eyebrow', models.CharField(blank=True, max_length=255)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('subheading', models.TextField(blank=True)),
                ('layout_variant', models.CharField(choices=[('GRID', 'Grid'), ('MASONRY', 'Masonry'), ('SLIDER', 'Slider')], default='GRID', max_length=16)),
            ],
            options={
                'verbose_name': 'Gallery section',
            },
            bases=('sections.section',),
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sections.section')),
                ('autoplay_seconds', models.PositiveSmallIntegerField(default=0, help_text='0 disables auto-advance. Ignored when there is a single slide.')),
            ],
            options={
                'verbose_name': 'Hero section',
            },
            bases=('sections.section',),
        ),
        migrations.CreateModel(
            name='IntroSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sections.section')),
                ('eyebrow', models.CharField(blank=True, max_length=255)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=100)),
                ('cta_url', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Intro section',
            },
            bases=('sections.section',),
        ),
        migrations.CreateModel(
            name='RichTextSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sections.section')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('updated_note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Rich text section',
            },
            bases=('sections.section',),
        ),
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sections.section')),
                ('eyebrow', models.CharField(blank=True, max_length=255)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('subheading', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Services section',
            },
            bases=('sections.section',),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['section_type', '-created_at'], name='sections_se_section_5b05ab_idx'),
        ),
        migrations.AddField(
            model_name='countersectionitem',
            name='counter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_items', to='content.counter'),
        ),
        migrations.AddField(
            model_name='faqsectionitem',
            name='faq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_items', to='content.faq'),
        ),
        migrations.AddField(
            model_name='featuredprojectitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_items', to='content.project'),
        ),
        migrations.AddField(
            model_name='gallerysectionitem',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='servicesectionitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_items', to='content.service'),
        ),
        migrations.AddField(
            model_name='countersectionitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sections.countersection'),
        ),
        migrations.AddField(
            model_name='ctasection',
            name='background_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='faqsectionitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sections.faqsection'),
        ),
        migrations.AddField(
            model_name='featuredprojectitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sections.featuredprojectssection'),
        ),
        migrations.AddField(
            model_name='gallerysectionitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sections.gallerysection'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='sections.herosection'),
        ),
        migrations.AddField(
            model_name='introsection',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='servicesectionitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sections.servicessection'),
        ),
        migrations.AddIndex(
            model_name='countersectionitem',
            index=models.Index(fields=['section', 'order'], name='sections_co_section_400946_idx'),
        ),
        migrations.AddConstraint(
            model_name='countersectionitem',
            constraint=models.UniqueConstraint(fields=('section', 'counter'), name='unique_counter_per_section'),
        ),
        migrations.AddIndex(
            model_name='faqsectionitem',
            index=models.Index(fields=['section', 'order'], name='sections_fa_section_6b85e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='faqsectionitem',
            constraint=models.UniqueConstraint(fields=('section', 'faq'), name='unique_faq_per_section'),
        ),
        migrations.AddIndex(
            model_name='featuredprojectitem',
            index=models.Index(fields=['section', 'order'], name='sections_fe_section_c12e96_idx'),
        ),
        migrations.AddConstraint(
            model_name='featuredprojectitem',
            constraint=models.UniqueConstraint(fields=('section', 'project'), name='unique_project_per_section'),
        ),
        migrations.AddIndex(
            model_name='gallerysectionitem',
            index=models.Index(fields=['section', 'order'], name='sections_ga_section_ba2539_idx'),
        ),
        migrations.AddConstraint(
            model_name='gallerysectionitem',
            constraint=models.UniqueConstraint(fields=('section', 'media'), name='unique_media_per_gallery_section'),
        ),
        migrations.AddIndex(
            model_name='heroslide',
            index=models.Index(fields=['section', 'order'], name='sections_he_section_ab766e_idx'),
        ),
        migrations.AddIndex(
            model_name='servicesectionitem',
            index=models.Index(fields=['section', 'order'], name='sections_se_section_c0fddd_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicesectionitem',
            constraint=models.UniqueConstraint(fields=('section', 'service'), name='unique_service_per_section'),
        ),
    ]
