# Generated by Django 6.1 on 2026-09-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_hero_variant_and_dual_cta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='autoplay_seconds',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 disables auto-advance. Ignored by the photographic variant.'),
        ),
    ]
