# Generated by Django 6.1 on 2026-09-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_search_extensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='layout',
            field=models.CharField(choices=[('full', 'Full width'), ('wide', 'Wide'), ('half', 'Half width'), ('portrait', 'Portrait')], default='half', max_length=16),
        ),
    ]
