
postgres=# CREATE DATABASE archethos;
CREATE DATABASE
postgres=# CREATE USER archethos_user WITH PASSWORD 'archethos@db';
CREATE ROLE
postgres=# CREATE USER archethos_user WITH PASSWORD 'PUT_A_STRONG_PASSWORD_HERE';^C
postgres=# ^C
postgres=# ^C
postgres=# ^C
postgres=# ALTER ROLE archethos_user SET client_encoding TO 'utf8';
ALTER ROLE archethos_user SET default_transaction_isolation TO 'read committed';
ALTER ROLE archethos_user SET timezone TO 'Asia/Kolkata';
ALTER ROLE
ALTER ROLE
ALTER ROLE