# Generated by Django 6.1 on 2026-09-27 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('media_library', '0001_initial'),
        ('projects', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('primary_cta_label', models.CharField(blank=True, max_length=100)),
                ('primary_cta_url', models.CharField(blank=True, max_length=255)),
                ('secondary_cta_label', models.CharField(blank=True, max_length=100)),
                ('secondary_cta_url', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliders', to='media_library.mediaasset')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_counters', models.JSONField(blank=True, default=list)),
                ('design_build_process', models.JSONField(blank=True, default=dict)),
                ('selected_work_title', models.CharField(blank=True, max_length=255)),
                ('selected_work_description', models.TextField(blank=True)),
                ('section_content', models.JSONField(blank=True, default=dict)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('featured_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_on_home_pages', to='projects.project')),
                ('featured_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_on_home_pages', to='services.service')),
                ('gallery', models.ManyToManyField(blank=True, related_name='home_pages', to='master.galleryitem')),
                ('selected_work', models.ManyToManyField(blank=True, related_name='selected_on_home_pages', to='projects.project')),
                ('sliders', models.ManyToManyField(blank=True, related_name='home_pages', to='home.slider')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='home_page_singleton')],
            },
        ),
    ]
