# Generated by Django 6.1 on 2026-09-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homecontentgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='label',
        ),
    ]
