# Generated by Django 6.1 on 2026-09-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_slider_label'),
        ('master', '0011_move_blogs_to_blogs_app'),
        ('projects', '0012_remove_project_construction_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecountersgroup',
            name='counters',
        ),
        migrations.RemoveConstraint(
            model_name='homecontentgroup',
            name='home_page_content_group_type_unique',
        ),
        migrations.RemoveField(
            model_name='homecountersgroup',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homegallerygroup',
            name='gallery_items',
        ),
        migrations.RemoveField(
            model_name='homegallerygroup',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homeprojectsgroup',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homeprojectsgroup',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='homeservicesgroup',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homeservicesgroup',
            name='services',
        ),
        migrations.RemoveField(
            model_name='workprocessstep',
            name='group',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='work_process_group',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='selected_gallery_items',
        ),
        migrations.AddField(
            model_name='homepage',
            name='design_build_process',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='homepage',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='home_pages', to='master.galleryitem'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_counters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='homepage',
            name='selected_work',
            field=models.ManyToManyField(blank=True, related_name='selected_on_home_pages', to='projects.project'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='selected_work_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='selected_work_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Counter',
        ),
        migrations.RemoveField(
            model_name='homecontentgroup',
            name='media',
        ),
        migrations.RemoveField(
            model_name='homecontentgroup',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homecontentgroup',
            name='secondary_media',
        ),
        migrations.DeleteModel(
            name='HomeCountersGroup',
        ),
        migrations.DeleteModel(
            name='HomeGalleryGroup',
        ),
        migrations.DeleteModel(
            name='HomeProjectsGroup',
        ),
        migrations.DeleteModel(
            name='HomeServicesGroup',
        ),
        migrations.DeleteModel(
            name='WorkProcessStep',
        ),
        migrations.DeleteModel(
            name='WorkProcessGroup',
        ),
        migrations.DeleteModel(
            name='HomeContentGroup',
        ),
    ]
