# Generated by Django 6.1 on 2026-08-31 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('social_urls', models.JSONField(blank=True, default=dict, help_text='{"instagram": "https://...", "linkedin": "https://..."}')),
                ('contacts', models.JSONField(blank=True, default=dict, help_text='{"emails": ["..."], "phones": ["..."], "whatsapp": "..."}')),
                ('header_links', models.JSONField(blank=True, default=list, help_text='[{"label": "Projects", "url": "/projects"}]')),
                ('footer_links', models.JSONField(blank=True, default=list, help_text='[{"heading": "Company", "links": [{"label": "...", "url": "..."}]}]')),
                ('head_inject', models.TextField(blank=True, help_text='Raw markup injected into <head>. Superuser only.')),
                ('body_inject', models.TextField(blank=True, help_text='Raw markup injected before </body>. Superuser only.')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media_library.mediaasset')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media_library.mediaasset')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, help_text='Set automatically on first publish. A future value schedules the item.', null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('robots_index', models.BooleanField(default=True)),
                ('robots_follow', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Admin-facing page name.', max_length=255)),
                ('slug', models.SlugField(help_text='Public identifier: /api/v1/public/pages/<slug>/. Matches the frontend route, e.g. "home", "about", "legal/privacy".', max_length=255, unique=True)),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_key', models.CharField(help_text='What this instance is for on this page, e.g. "main_hero", "bottom_cta". Distinct from the section\'s type, which says which component renders it. Lets one page carry two CTAs.', max_length=100)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_visible', models.BooleanField(default=True, help_text='Hide on this page without detaching it or affecting other pages.')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_sections', to='pages.page')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='page_usages', to='sections.section')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['status', 'published_at'], name='pages_page_status_de97e2_idx'),
        ),
        migrations.AddIndex(
            model_name='pagesection',
            index=models.Index(fields=['page', 'order'], name='pages_pages_page_id_af72a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagesection',
            constraint=models.UniqueConstraint(fields=('page', 'section_key'), name='unique_page_section_key'),
        ),
    ]
