# Generated by Django 6.1 on 2026-09-07 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpresencesection',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='aboutpresencesection',
            name='tone',
        ),
        migrations.RemoveField(
            model_name='contactformsection',
            name='tone',
        ),
        migrations.RemoveField(
            model_name='designbuildsection',
            name='tone',
        ),
        migrations.RemoveField(
            model_name='gallerygridsection',
            name='tone',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='homelocationssection',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='homeprojectssection',
            name='tone',
        ),
        migrations.RemoveField(
            model_name='homeservicessection',
            name='tone',
        ),
        migrations.RemoveField(
            model_name='journalfeaturedsection',
            name='tone',
        ),
        migrations.RemoveField(
            model_name='journallistsection',
            name='tone',
        ),
        migrations.RemoveField(
            model_name='locationslistsection',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='locationslistsection',
            name='tone',
        ),
        migrations.RemoveField(
            model_name='missionvisionsection',
            name='tone',
        ),
        migrations.RemoveField(
            model_name='philosophysection',
            name='tone',
        ),
        migrations.RemoveField(
            model_name='processsection',
            name='tone',
        ),
        migrations.RemoveField(
            model_name='projectindexsection',
            name='tone',
        ),
        migrations.RemoveField(
            model_name='serviceindexsection',
            name='tone',
        ),
        migrations.RemoveField(
            model_name='statssection',
            name='tone',
        ),
        migrations.RemoveField(
            model_name='studiostorysection',
            name='tone',
        ),
        migrations.RemoveField(
            model_name='vastusection',
            name='tone',
        ),
        migrations.RemoveField(
            model_name='visitingsection',
            name='tone',
        ),
        migrations.RemoveField(
            model_name='whathappenssection',
            name='tone',
        ),
    ]
