# Generated by Django 6.1 on 2026-08-31 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_seed_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(help_text='Public identifier: /api/v1/public/pages/<slug>/. Matches the frontend route, e.g. "home", "about", "legal/privacy".', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Use lowercase letters, numbers and hyphens. Nested routes are allowed, e.g. "legal/privacy". No leading or trailing slash.', regex='^[a-z0-9]+(?:-[a-z0-9]+)*(?:/[a-z0-9]+(?:-[a-z0-9]+)*)*$')]),
        ),
    ]
