# Generated by Django 6.1 on 2026-09-20 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0007_media_thumbnail_file'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='service',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='service',
            name='hero_heading',
        ),
        migrations.RemoveField(
            model_name='service',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='index_image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='service',
            name='number',
        ),
        migrations.RemoveField(
            model_name='service',
            name='order',
        ),
        migrations.RemoveField(
            model_name='service',
            name='process_eyebrow',
        ),
        migrations.RemoveField(
            model_name='service',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title_lines',
        ),
        migrations.AddField(
            model_name='service',
            name='eyebrow',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='how_it_moves',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_images', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ServicesGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_gallery_items', to='media_library.mediaasset')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='services.service')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceWorkStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_stage_media', to='media_library.mediaasset')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_stages', to='services.service')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='ServicesWorkProcess',
        ),
    ]
