# Generated by Django 6.1 on 2026-09-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sections',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
