# Generated by Django 6.1 on 2026-09-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_options_remove_service_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='how_project_moves',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
