# Generated by Django 6.1 on 2026-09-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceworkstage',
            name='image_side',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], default='', max_length=5),
        ),
    ]
