# Generated by Django 6.1 on 2026-08-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_type', models.CharField(choices=[('CONTACT', 'Contact'), ('CONSULTATION', 'Consultation'), ('PROJECT', 'Project enquiry'), ('CAREER', 'Career'), ('GENERAL', 'General')], db_index=True, default='CONTACT', max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('source_page', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['form_type', '-created_at'], name='enquiries_e_form_ty_7b590e_idx'), models.Index(fields=['is_read', '-created_at'], name='enquiries_e_is_read_1977d8_idx')],
            },
        ),
    ]
