# Generated by Django 6.1 on 2026-09-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_smtp_enquiry_workflow_and_replies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='project_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
