# Generated by Django 6.1 on 2026-09-27 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(blank=True, max_length=255)),
                ('hero_title', models.CharField(blank=True, max_length=255)),
                ('hero_description', models.TextField(blank=True)),
                ('who_we_are_title', models.CharField(blank=True, max_length=255)),
                ('who_we_are_description', models.JSONField(blank=True, default=dict)),
                ('who_we_are_media', models.URLField(blank=True)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('founders_section', models.JSONField(blank=True, default=dict)),
                ('approach', models.JSONField(blank=True, default=dict)),
                ('philosophy_eyebrow', models.CharField(blank=True, max_length=255)),
                ('philosophy_title', models.CharField(blank=True, max_length=255)),
                ('philosophy_short_description', models.TextField(blank=True)),
                ('philosophy_description', models.JSONField(blank=True, default=dict)),
                ('philosophy_media', models.URLField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('hero_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_hero_media', to='media_library.mediaasset')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='about_page_singleton')],
            },
        ),
    ]
