# Generated by Django 6.1 on 2026-09-20 15:49

import json

from django.db import migrations, models


def normalize_rich_content(apps, schema_editor):
    AboutPage = apps.get_model("about", "AboutPage")
    for page in AboutPage.objects.all():
        changed = []
        for field in ("mission", "vision"):
            value = getattr(page, field)
            if isinstance(value, str):
                setattr(page, field, json.dumps({"title": "", "description": value, "image": ""}))
                changed.append(field)
        value = page.philosophy_description
        if isinstance(value, str):
            page.philosophy_description = json.dumps({
                "blocks": ([{"type": "paragraph", "data": {"text": value}}] if value.strip() else [])
            })
            changed.append("philosophy_description")
        if changed:
            page.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_flatten_aboutpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='cta_description',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='cta_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='cta_label',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='cta_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='cta_url',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='founder_credentials',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='founder_eyebrow',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='founder_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='founder_message',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='founder_name',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='founder_role',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='founder_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='philosophy_cta_label',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='philosophy_cta_url',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='philosophy_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='philosophy_supporting_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='presence_cta_label',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='presence_cta_url',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='presence_description',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='presence_eyebrow',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='presence_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='slider',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='studio_description',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='studio_eyebrow',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='studio_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='studio_lead',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='studio_supporting_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='studio_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='work_process_group',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='approach',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='founders_section',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='philosophy_media',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='philosophy_short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='who_we_are_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='who_we_are_media',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='who_we_are_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(normalize_rich_content, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='aboutpage',
            name='mission',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='philosophy_description',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='philosophy_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='vision',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
