# Generated by Django 6.1 on 2026-09-20 15:57

from django.db import migrations


def move_mission_and_vision_into_sections(apps, schema_editor):
    AboutPage = apps.get_model("about", "AboutPage")
    for page in AboutPage.objects.all():
        sections = page.sections if isinstance(page.sections, list) else []
        changed = False
        for field in ("mission", "vision"):
            value = getattr(page, field)
            if not value:
                continue
            section = dict(value) if isinstance(value, dict) else {"description": value}
            section.setdefault("type", field)
            sections.insert(0 if field == "mission" else 1, section)
            changed = True
        if changed:
            page.sections = sections
            page.save(update_fields=["sections"])


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_remove_aboutpage_cta_description_and_more'),
    ]

    operations = [
        migrations.RunPython(move_mission_and_vision_into_sections, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='aboutpage',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='vision',
        ),
    ]
