# Generated by Django 6.1 on 2026-09-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_blogspage_featured_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogspage',
            name='featured_blogs',
            field=models.ManyToManyField(blank=True, related_name='featured_on_blogs_pages', to='blogs.blog'),
        ),
    ]
